{% set name = "pydantic_factories" %}
{% set version = "1.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydantic-factories-{{ version }}.tar.gz
  sha256: 0ac03224ba5677de3d43d304beb4648c0dcbdf0e997e5c6d34af0d09794ccb81

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - xeger >=0.3.5,<1.0.0
    - faker
    - pydantic
    - python >=3.6,<4.0
    - typing-extensions

test:
  imports:
    - pydantic_factories
    - pydantic_factories.constraints
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Goldziher/pydantic-factories
  summary: Mock data generation for pydantic based models
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
    - ivergara
